pythonTodo/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('todo/', include('todo.urls')),
    path('admin/', admin.site.urls),
]

todo/urls.py
from django.urls import path

from . import views

app_name = 'todo'
urlpatterns = [
    path('', views.index, name='index'),
    # ex: /tasks/
    path('tasks/', views.tasks, name='tasks'),
    #  # ex: /add_task/
    # path('addtask/', views.addtask, name='addtask'),
]

todo/models.py
from django.db import models

# Create your models here.


class Task(models.Model):
    task_name = models.CharField(max_length=200,null=True,blank=True)
    task_date = models.CharField(max_length=100,null=True,blank=True)

todo/views.py
# from django.shortcuts import render

from django.http import HttpResponse
# from django.template import loader
from django.shortcuts import render

from .models import Task

def index(request):
    return render(request, 'todo/index.html')

def tasks(request):
    
    # for e in Task.objects.all():
    #   print(e.task_date)
    # template = loader.get_template('todo/index.html')
    # context = {
    #     'todo_list': todo_list,
    # }
    # return HttpResponse(template.render(context, request))
    # print(request.POST)
    # task_id= request.GET.get("id")
    # print(task_id)

    task_text = request.POST.get("task_text")
    task_time = request.POST.get("task_time")

    if(task_text and task_time != None):
        task = Task(task_name=task_text, task_date=task_time)
        task.save()
    
    todo_list = Task.objects.order_by('task_name')

    context = {'todo_list': todo_list}
    return render(request, 'todo/tasks.html', context)

todo/templates/todo/index.html
<h1>Todo App</h1>
<br/><br/>
<a href="{% url 'todo:tasks' %}"><button>Get Started</button></a>

todo/templates/todo/tasks.html
<html>
  {% load static %}
  <head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{%  static  'css/style.css'  %}" >

    <title>Todo App</title>
  </head>
  <div class="row">
    <div class="col-md-12">
      <h2>Things To Do...</h2>
      <div class="main-todo-input-wrap">
       <!-- <div class="main-todo-input fl-wrap">
          <div class="main-todo-input-item"> -->
            <form action = "" method = "POST">
              {% csrf_token %} 
              <input type="text" class="form-control todo-task" name="task_text" id="exampleInputEmail1" placeholder="What are you going to do?">  
              <input type="text" class="form-control todo-task" name="task_time" id="exampleInputEmail2" placeholder="When are you going to do?"> 
            <button id="submit" type="submit" class=" add-task btn btn-primary">Add task</button>      
          <!-- </div>           -->
        </form>
        <!-- </div> -->
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      {% if todo_list %}
      <div class="main-todo-input-wrap">
        {% for task in todo_list %}
        <div class="main-todo-input fl-wrap">
          <ul id="list-items">
            <div class="todo-listing">
              <li class="todo-text">{{ task.task_name }}</li><li class="todo-text">{{ task.task_date }}</li><a href="#"><i id="{{task.id}}" name="remove" class="fas fa-trash remove"></i><i class="fas fa-check-circle taskcheck"></i></a>              
            </div>
          </ul>
        </div>
          {% endfor %}     
      </div>
      {% endif %}    
    </div>
  </div>
</html>